export const POKEMON_TYPES_COLORS: Record<string, string> = {
  normal: 'white',
  fire: 'red',
  water: 'blue',
  grass: 'green',
  electric: 'yellow',
  ice: 'blue',
  fighting: 'green',
  poison: 'green',
  ground: 'yellow',
  flying: 'yellow',
  psychic: 'yellow',
  bug: 'yellow',
  rock: 'yellow',
  ghost: 'blue',
  dragon: 'blue',
  dark: 'blue',
  steel: 'blue',
  fairy: 'blue',
}
